// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomslz6xZYVX-KLeAiiaFJjuL4zYW3m64',
    appId: '1:560287735840:web:13777112d6a7d64ca25c45',
    messagingSenderId: '560287735840',
    projectId: 'latihan-1e292',
    authDomain: 'latihan-1e292.firebaseapp.com',
    storageBucket: 'latihan-1e292.appspot.com',
    measurementId: 'G-RM5V1JFTQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyX5F1mSoza8Sclm_C5nvmdDKWE4U7uoM',
    appId: '1:560287735840:android:0dd9288f7b027b8ca25c45',
    messagingSenderId: '560287735840',
    projectId: 'latihan-1e292',
    storageBucket: 'latihan-1e292.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURm70vXaTOkx0PVKQUsoOjJ0BXkTNQA8',
    appId: '1:560287735840:ios:77645dec6d9de0b2a25c45',
    messagingSenderId: '560287735840',
    projectId: 'latihan-1e292',
    storageBucket: 'latihan-1e292.appspot.com',
    iosClientId: '560287735840-4upkgiqva4ebk478qe0lmc25bfkatvkh.apps.googleusercontent.com',
    iosBundleId: 'com.slynkle.latihan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURm70vXaTOkx0PVKQUsoOjJ0BXkTNQA8',
    appId: '1:560287735840:ios:77645dec6d9de0b2a25c45',
    messagingSenderId: '560287735840',
    projectId: 'latihan-1e292',
    storageBucket: 'latihan-1e292.appspot.com',
    iosClientId: '560287735840-4upkgiqva4ebk478qe0lmc25bfkatvkh.apps.googleusercontent.com',
    iosBundleId: 'com.slynkle.latihan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDomslz6xZYVX-KLeAiiaFJjuL4zYW3m64',
    appId: '1:560287735840:web:05c2c89292f9238ca25c45',
    messagingSenderId: '560287735840',
    projectId: 'latihan-1e292',
    authDomain: 'latihan-1e292.firebaseapp.com',
    storageBucket: 'latihan-1e292.appspot.com',
    measurementId: 'G-77P0MHEQ4E',
  );
}
